name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:     # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/bia-pain-bache/BPB-Worker-Panel.git
          git fetch upstream
          git checkout main
          git merge upstream/main

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
